[package]
name = "reedline-suspend"
version = "0.1.0"
edition = "2021"

[dependencies]
reedline = "0.40.0"
nix = { version = "0.30.0", features = ["signal"] }
crossterm = "0.29.0"
thiserror = "1.0.56"